# Site settings
title: Jan's Place
header-img: img/home-bg.jpg
email: j.halozan.services@gmail.com
copyright_name: JanHalozan
description: "A mix of computer science related articles & projects, you might even find something interesting. Also home of me - Jan Halozan."
baseurl: ""
url: "http://janhalozan.com"
twitter_username: JanHalozan
github_username:  JanHalozan
facebook_username:  JanHalozan

# Google Analytics
google_tracking_id: UA-27826743-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
